### ISSUE TITLE
关于vuex的替代方案

### ISSUE THREAD

**Issue by nikolausliu** [weizhanzhan/vue3-ts-template-h5#3]
都说provide/inject可以替代vuex，但是provide/inject貌似只能在组件的setup选项内使用吧？我如果想在其他地方使用就不行了。举个很常见的业务场景：
axios请求拦截器里给所有请求在请求头里带上token，用vuex我可以在拦截器逻辑所在的js文件里引用store。但是provide/inject在这里就用不了了吧

**Comment by weizhanzhan** [comment]
> 都说provide/inject可以替代vuex，但是provide/inject貌似只能在组件的setup选项内使用吧？我如果想在其他地方使用就不行了。举个很常见的业务场景：
> axios请求拦截器里给所有请求在请求头里带上token，用vuex我可以在拦截器逻辑所在的js文件里引用store。但是provide/inject在这里就用不了了吧

你好，刚看到你提的问题啊，我先说下的观点啊，第一点：provide和inject是你说的情况不假，仅局限于vue中去使用，这是没有问题的，但是他起的作用仅仅是传递的一个效果，一边注入，一边依赖，这个是和数据没有关系的，而我们的是数据源是单独定义的，也可以理解为一个小的store，并且vue3有了reactive、ref等composition api的加持，实现一个数据互通的store更简单了，所以你所担心的问题也解决了，可以在axios配置文件里，引入你定义的哪个对象就可以直接使用了
