### ISSUE TITLE
npm run serve 报错

### ISSUE THREAD

**Issue by fuerpeng** [weizhanzhan/vue3-ts-template-h5#4]
TypeError: compilation.templatesPlugin is not a function
  
  感觉npm版本控制越来越差了。。

**Comment by fuerpeng** [comment]
一个项目过段时间再安装依赖就会出各种各样的问题，yarn就比npm好多了

**Comment by weizhanzhan** [comment]
> TypeError: compilation.templatesPlugin is not a function
> 
> 感觉npm版本控制越来越差了。。

确实，这个版本还是vue3的测试版本

**Comment by weizhanzhan** [comment]
报错的处理好了，typescript版本有问题
