### ISSUE TITLE
readme.md Anchor point jump failed

### ISSUE THREAD

**Issue by lvfangren** [weizhanzhan/vue3-ts-template-h5#5]
在readme中部分章节（CompositionApi,....）通过锚点跳转失效。

**Comment by lvfangren** [comment]
预览demo里请求404。 没做环境变量区分，把baseURL写死了 const baseURL = "http://localhost:8080/api";

**Comment by lvfangren** [comment]
也许可以看下这个： https://cloud.tencent.com/developer/article/1883873

**Comment by weizhanzhan** [comment]
你好，我刚看了下，带符号的是有问题的，大写字母可以跳转的，你那边大写字母也不可以吗

**Comment by weizhanzhan** [comment]
> aseURL写死了 const b

对，因为这块后端还没完善，目前还没对接

**Comment by lvfangren** [comment]
> 你好，我刚看了下，带符号的是有问题的，大写字母可以跳转的，你那边大写字母也不可以吗

大写字母好像是不可以的。

**Comment by lvfangren** [comment]
hello，正好前几天碰见的小问题可以一起分享学习下😂；1: 刘海屏的手机全屏与否的问题（参见：https://www.webhek.com/post/the-notch-and-css.html）； 2：使用了postcss-px-to-viewport 来转换单位，但是一些特殊的情况没法转化（或者不需要转换），可以在文档里加下说明下或者把配置项打开暴露出来
