### ISSUE TITLE
提个文档上看到的问题

### ISSUE THREAD

**Issue by Xyuan-abs** [weizhanzhan/vue3-ts-template-h5#7]
![image](https://user-images.githubusercontent.com/64180387/156501105-a51a9607-024a-4217-a3c5-4c18c0de121e.png)

在axios配置上，接口返回的是response.data。从配置上判断，response.data的数据格式应该是
```
{
  code:200,
  msg:xxx,
  [具体数据的key]: 具体数据
}
```

![image](https://user-images.githubusercontent.com/64180387/156501184-225942d1-6634-4b81-a763-9ae0aba6c8b0.png)
在api文件里，具体接口定义的返回值类型是 ResourceOption，ResourceOption与response.data类型明显不一致，ResourceOption应该是`具体数据`的类型

不知道我又没有理解错

**Comment by Xyuan-abs** [comment]
可以这样解决

```ts
interface ResponseData<T> {
  code: number
  success: boolean
  data: T
}

interface ResourceOption{
  title:string;
  logo:string;
}

export const getResouceList = () => {
  return request<ResponseData<ResourceOption[]>>({
    url: "api/resource/list",
    method: "get"
  });
};
```

**Comment by weizhanzhan** [comment]
> ![image](https://user-images.githubusercontent.com/64180387/156501105-a51a9607-024a-4217-a3c5-4c18c0de121e.png)
> 
> 在axios配置上，接口返回的是response.data。从配置上判断，response.data的数据格式应该是
> 
> ```
> {
>   code:200,
>   msg:xxx,
>   [具体数据的key]: 具体数据
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/64180387/156501184-225942d1-6634-4b81-a763-9ae0aba6c8b0.png) 在api文件里，具体接口定义的返回值类型是 ResourceOption，ResourceOption与response.data类型明显不一致，ResourceOption应该是`具体数据`的类型
> 
> 不知道我又没有理解错

对的，包括你下面理解的也是对的，因为这个东西数据格式需要根据的数据类型来具体配置，没考虑这么周全，我这边改一下
